### ISSUE TITLE
Imaging state not getting selected

### ISSUE THREAD

**Issue by hamid13r** [eisfabian/SPACEtomo#1]
Dear Fabian,

I am trying to set up SPACEtomo after updating our PACEtomo to 1.7 (which seems to be running smoothly). 

One problem I ran into is to take the whole grid montage. The imaging state for this montage somwhow cannot be selected in the code. I suspect the reason is that our atlas imaging state is not set up in the low-dose mode.  

At the moment, I worked around this by going to that imaging state and setting the `WG_image_stae` to a number that does not exist so it stays in the imaging state i chose. 

There is another problem I need to center the beam when I load the final imaging state so the switch itself seems to be problematic. Is this something I can solve in SerialEM?

Best,
Hamid

**Comment by eisfabian** [comment]
Dear Hamid!

Thanks for reaching out!
Yes, I always used a separate low mag (82x) image state (non low dose) to take my whole grid montages. And then switch to my low-dose image state to do collection.

People have suggested to utilize the Search mode in Low Dose to get around switching image states, but I have not played around with that yet.

To avoid recentering the beam I recommend redoing the alignments, or aligning the beam shift for the low dose mode and spreading it in the whole grid image state.
But, you can also add a MoveBeamByMicrons command in the script after     
```
    sem.GoToImagingState(str(mic_params.MM_image_state))
    sem.GoToLowDoseArea("V")
```
in case your beam shift is reproducible.

Hope this helps!
Best,
Fabian

**Comment by hamid13r** [comment]
Thank you, it might be worth looking into. However, the code skips the whole grid if it sees the file so we can manually center the beam and make it work. Of course, this will be done without multi-grid functionality.

**Comment by eisfabian** [comment]
Yes, multigrid functionality is on my to-do list, I think people still want some control and options for intervention for now, so I will work towards more user interactions first.

**Comment by hamid13r** [comment]
Yes I also believe the most popular automation level will be level 4 which saves the most effort and time but keeps the user input in the important steps. 

I wasn't clear originally, I am unable to load the atlas imaging state either by a number or the name input. Is there a way to test this, like a short script?

**Comment by eisfabian** [comment]
I'm not sure what's going wrong with your imaging states.
Do you get an error message?

You can only play around with the GoToImagingState command and see what works. Maybe try redoing your image states in a fresh settings file and have a look?
