### ISSUE TITLE
WG_offset_via_IM does not work

### ISSUE THREAD

**Issue by hamid13r** [eisfabian/SPACEtomo#3]
Hi Fabian,

Sorry, I am submitting all of my questions together. When I try to have the parameter `WG_offset_via_IM = True` I get an error as 

`Error trying to reduce image: reduction factor is not in allowed range in statement: ReduceImage(A, 1202.931077)`

It shows as a pop-up and there is nothing in the log. 

This goes away when I set `WG_offset_via_IM = False`.

Any ideas how to solve this?

Best,
Hamid

**Comment by eisfabian** [comment]
Hi Hamid,

What magnification did you set for IM_mag_index? This number seems way too large.

**Comment by hamid13r** [comment]
I was using 580 (at least I thought I was using 580!).

**Comment by eisfabian** [comment]
Did you use the IM_mag_index = 10?
This might be a different mag depending on your SerialEM properties file. Please double check!

I should make more clear in the settings that this is dependent on your microscope setup.

**Comment by hamid13r** [comment]
I used 16 which I believe is 580x in our krios.

**Comment by eisfabian** [comment]
Is the pixel size calibrated at that mag? You can check what it says in the properties file or send it to me.
