### ISSUE TITLE
Resuming SPACEtomo1.1 after step2

### ISSUE THREAD

**Issue by hamid13r** [eisfabian/SPACEtomo#7]
Dear Fabian, 

I just updated our installation to 1.1 and I am glad to inform you my problem with the "blank" medium mag montages is resolved. 

While I am trying to move forwards in steps and solve installation/environment problems one at the time, is there a way of resuming a collection? For PACEtomo_select_targets.py we could just go on the txt item and run the script for editing the target file, is there an equivalent action in SPACEtomo that i missed? at the moment I need to start over from the atlas every time. 

Thank you in advance and congratulations on the amazing work!

Best,
Hamid

**Comment by eisfabian** [comment]
Hi Hamid,

Yes, in theory it should detect that there already is an atlas and skip this step. There might still be some issues with this in v1.1. Version 1.2 will be much more robust for restarting a SPACE run and automatically skipping unnecessary steps.

Either way, there is no text file with the run data at this point. It checks for navigator entries and map files already present to determine what was done and what still has to be done.

Again, v1.2 should be coming soon with a lot of improvements. I just want to get in 1 or 2 more sessions to make sure it runs smoothly.

Thanks again and best wishes,
Fabian

**Comment by hamid13r** [comment]
I cannot wait to work with SPACEtomo  1.2, thanks!

**Comment by eisfabian** [comment]
SPACEtomo v1.2 is finally out. I will close the issue for now!
